'use client'

import { SignatureData } from '@/lib/signature-data'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Label } from '@/components/ui/label'
import { FieldGroup, Field, FieldLabel } from '@/components/ui/field'

const themes = [{ name: 'Ocean', primary: '#0f172a', secondary: '#64748b', accent: '#2563eb' }, { name: 'Forest', primary: '#14532d', secondary: '#4d7c0f', accent: '#16a34a' }, { name: 'Plum', primary: '#581c87', secondary: '#7e22ce', accent: '#db2777' }, { name: 'Gold', primary: '#422006', secondary: '#92400e', accent: '#d97706' }]

type Change = (field: keyof SignatureData, value: string | number | boolean) => void

export function BrandingControls({ data, onChange }: { data: SignatureData; onChange: Change }) {
  const readFile = (field: keyof SignatureData, file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => onChange(field, String(reader.result)); reader.readAsDataURL(file) }
  return <div className="flex flex-col gap-4">
    <Card><CardHeader><CardTitle className="text-lg">Employee Profile</CardTitle><CardDescription>Separate employee photo with a crop-safe preview.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><label className="flex min-h-28 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-primary/40 bg-primary/5 p-4 text-center"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={e => readFile('employeePhoto', e.target.files?.[0])} />{data.employeePhoto ? <img src={data.employeePhoto} alt="Employee preview" className="size-16 rounded-full object-cover" /> : <><span className="font-medium">Upload Employee Photo</span><span className="text-xs text-muted-foreground">PNG, JPG, JPEG or WebP</span></>}</label><FieldGroup><Field><FieldLabel htmlFor="employeePhotoUrl">Use employee image from URL</FieldLabel><Input id="employeePhotoUrl" value={data.employeePhoto.startsWith('data:') ? '' : data.employeePhoto} onChange={e => onChange('employeePhoto', e.target.value)} placeholder="https://company.com/employee.jpg" /></Field></FieldGroup><div className="flex items-center justify-between"><Label htmlFor="show-photo">Show Employee Photo</Label><Switch id="show-photo" checked={data.showEmployeePhoto} onCheckedChange={value => onChange('showEmployeePhoto', value)} /></div><div className="grid grid-cols-2 gap-3"><FieldGroup><Field><FieldLabel>Photo Shape</FieldLabel><select className="h-9 rounded-md border bg-background px-3 text-sm" value={data.photoShape} onChange={e => onChange('photoShape', e.target.value)}><option value="circle">Circular</option><option value="rounded">Rounded</option><option value="square">Square</option></select></Field></FieldGroup><FieldGroup><Field><FieldLabel>Photo Size: {data.avatarSize}px</FieldLabel><Input type="range" min="60" max="100" value={data.avatarSize} onChange={e => onChange('avatarSize', Number(e.target.value))} /></Field></FieldGroup></div></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Company Branding</CardTitle><CardDescription>Keep logos contained and proportional in preview and export.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><label className="flex min-h-32 cursor-pointer flex-col items-center justify-center rounded-xl border border-dashed border-primary/40 bg-primary/5 p-4 text-center"><input className="sr-only" type="file" accept="image/png,image/jpeg,image/svg+xml,image/webp" onChange={e => readFile('companyLogo', e.target.files?.[0])} />{data.companyLogo ? <img src={data.companyLogo} alt="Company logo preview" className="max-h-20 max-w-40 object-contain" /> : <><span className="font-medium">Upload Company Logo</span><span className="text-xs text-muted-foreground">PNG, SVG, JPG or WebP</span></>}</label><FieldGroup><Field><FieldLabel htmlFor="logoUrl">Use logo from URL</FieldLabel><Input id="logoUrl" value={data.logoUrl} onChange={e => onChange('logoUrl', e.target.value)} placeholder="https://company.com/logo.png" /></Field></FieldGroup><FieldGroup><Field><FieldLabel>Logo Width: {data.logoSize}px</FieldLabel><Input type="range" min="72" max="240" value={data.logoSize} onChange={e => onChange('logoSize', Number(e.target.value))} /></Field></FieldGroup><FieldGroup><Field><FieldLabel>Logo Height: {data.logoHeight}px</FieldLabel><Input type="range" min="48" max="160" value={data.logoHeight} onChange={e => onChange('logoHeight', Number(e.target.value))} /></Field></FieldGroup><FieldGroup><Field><FieldLabel>Logo Alignment</FieldLabel><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={data.logoAlignment} onChange={e => onChange('logoAlignment', e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></Field></FieldGroup><div className="flex items-center justify-between"><Label htmlFor="show-logo">Show Company Logo</Label><Switch id="show-logo" checked={data.showCompanyLogo} onCheckedChange={value => onChange('showCompanyLogo', value)} /></div>{(data.companyLogo || data.logoUrl) && <Button variant="outline" onClick={() => { onChange('companyLogo', ''); onChange('logoUrl', '') }}>Remove Logo</Button>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Tech Professional Settings</CardTitle><CardDescription>Control the hierarchy and icon treatment.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex items-center justify-between"><Label htmlFor="show-address">Show Address</Label><Switch id="show-address" checked={data.showAddress} onCheckedChange={value => onChange('showAddress', value)} /></div><div className="flex items-center justify-between"><Label htmlFor="show-socials">Show Social Media</Label><Switch id="show-socials" checked={data.showSocials} onCheckedChange={value => onChange('showSocials', value)} /></div><div className="flex items-center justify-between"><Label htmlFor="show-icons">Show Contact Icons</Label><Switch id="show-icons" checked={data.showContactIcons} onCheckedChange={value => onChange('showContactIcons', value)} /></div><div className="flex items-center justify-between"><Label htmlFor="show-tagline">Show Company Tagline</Label><Switch id="show-tagline" checked={data.showTagline} onCheckedChange={value => onChange('showTagline', value)} /></div><FieldGroup><Field><FieldLabel>Contact Layout</FieldLabel><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={data.contactLayout} onChange={e => onChange('contactLayout', e.target.value)}><option value="vertical">Vertical</option><option value="compact">Compact</option></select></Field></FieldGroup><FieldGroup><Field><FieldLabel>Social Icon Style</FieldLabel><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" value={data.socialIconStyle} onChange={e => onChange('socialIconStyle', e.target.value)}><option value="monochrome">Monochrome</option><option value="brand">Brand Color</option></select></Field></FieldGroup></CardContent></Card>
    <Card><CardHeader><CardTitle className="text-lg">Brand Colors</CardTitle><CardDescription>Apply a preset or tune each color.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid grid-cols-2 gap-2">{themes.map(theme => <Button key={theme.name} variant="outline" onClick={() => { onChange('primaryColor', theme.primary); onChange('secondaryColor', theme.secondary); onChange('accentColor', theme.accent) }}><span className="size-3 rounded-full" style={{ backgroundColor: theme.accent }} />{theme.name}</Button>)}</div>{(['primaryColor', 'secondaryColor', 'accentColor', 'textColor'] as const).map(field => <FieldGroup key={field}><Field><FieldLabel htmlFor={field}>{field.replace('Color', ' Color')}</FieldLabel><div className="flex gap-2"><Input id={field} type="color" value={data[field]} onChange={e => onChange(field, e.target.value)} className="size-9 cursor-pointer p-1" /><Input value={data[field]} onChange={e => onChange(field, e.target.value)} /></div></Field></FieldGroup>)}</CardContent></Card>
  </div>
}
